routes:
  - route: "^.+\\.(js|css|svg|woff|woff2|eot|ttf)$"
    #  cache static assets for 20 years
    headers:
      Cache-Control: "max-age=630720000, no-transform, public"
    gzip: true
  - route: "^.+\\.(png|jpg|pdf|html|json|xml|mp4|mp3)$"
    headers:
      Cache-Control: "s-maxage=60, no-transform, public"
      gzip: true
