baseURL = "https://mikeder.net"
languageCode = "en-us"
title = "Mike Eder's Weblog"
theme = "purehugo"
copyright = ""
paginate = 5
enableEmoji = true
enableGitInfo = false

[outputs]
  archive = ["HTML"]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  posts = ["HTML", "RSS"]

[params]
  author = "Mike Eder"
  subtitle = "think/work log for my coding, homelab and music adventures."
  twitterName = "sqweebking"
  githubName = "mikeder"
  linkedinName = "michael-eder-283831b8"
  hideSidebarIconText = true
  # "light" or "dark"
  defaultTheme = "dark"

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/pages/resume"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"

[languages]
  [languages.en]
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
